### ISSUE TITLE
Team-Aries Code Review

### ISSUE THREAD

**Issue by jstloyal** [kblycaglayan/HTML-CSS-capstone-project-Conference-page#3]
-- After completion, it is a well written code from our observation.
-- The designs are simple and elegant.
-- We suggest the whole HTML files should be in a single folder like the stylesheet folder.
NICE JOB!

**Comment by kubilaycaglayan** [comment]
Thank you for your advice, I will care foldering more.
It is great to have a team and get comments like this.
With all my respect...
