### ISSUE TITLE
30 Mar 2020 - Team 100 - The Aries - Peer to Peer Review

### ISSUE THREAD

**Issue by kevcap** [kblycaglayan/HTML-CSS-capstone-project-Conference-page#6]
# Hey @kblycaglayan,  your work looks awesome! 💥 Congratulations for the great work, I really liked it! 😎 👍
##Team comments:
```
All members liked your code, it's really a well-written code;
Keep up that good work!
```
🙋 Anytime, anything, just reach me by slack, [instagram](instagram.com/kevinnnnmn/), [LinKevin](linkedin.com/in/kevinnn) or 
[![Twitter Follow](https://img.shields.io/twitter/follow/kevinfrontend?label=Follow%20Kevin%20on%20Twitter&style=social)](https://twitter.com/kevinfrontend)

Keep Healthy 🏊 and Keep Happy 😄!

**Comment by kubilaycaglayan** [comment]
Thanks for your feedback team.
I appreciate!
With all my respect...
